<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Nomenclature;

class NomenclatureStatusSeeder extends Seeder
{
    public function run()
    {
        $map = [
            // =========================
            // NOT AKTIF (Broken/Eliminated)
            // =========================
            '2H1P11' => 'Not Aktif (Broken/Eliminated)',
            '2H1P21' => 'Not Aktif (Broken/Eliminated)',
            '2J1P11' => 'Not Aktif (Broken/Eliminated)',
            '2J1P21' => 'Not Aktif (Broken/Eliminated)',
            '2K1S02' => 'Not Aktif (Broken/Eliminated)',
            '2R1P21' => 'Not Aktif (Broken/Eliminated)',
            '2U1P01' => 'Not Aktif (Broken/Eliminated)',
            '2U1P11' => 'Not Aktif (Broken/Eliminated)',
            '2U1P21' => 'Not Aktif (Broken/Eliminated)',
            '2U1P31' => 'Not Aktif (Broken/Eliminated)',
            '2U1P51' => 'Not Aktif (Broken/Eliminated)',
            '2U1P81' => 'Not Aktif (Broken/Eliminated)',
            '2W1P11' => 'Not Aktif (Broken/Eliminated)',
            '2W1P21' => 'Not Aktif (Broken/Eliminated)',
            '2W1P31' => 'Not Aktif (Broken/Eliminated)',
            '2W1P33' => 'Not Aktif (Broken/Eliminated)',
            '2W1P41' => 'Not Aktif (Broken/Eliminated)',
            '3H2P11' => 'Not Aktif (Broken/Eliminated)',
            '3H2P21' => 'Not Aktif (Broken/Eliminated)',
            '3J2P11' => 'Not Aktif (Broken/Eliminated)',
            '3J2P21' => 'Not Aktif (Broken/Eliminated)',
            '3J2P31' => 'Not Aktif (Broken/Eliminated)',
            '3K2S02' => 'Not Aktif (Broken/Eliminated)',
            '3P1P11' => 'Not Aktif (Broken/Eliminated)',
            '3P1P21' => 'Not Aktif (Broken/Eliminated)',
            '3P1P31' => 'Not Aktif (Broken/Eliminated)',
            '3P1P41' => 'Not Aktif (Broken/Eliminated)',
            '3R2P21' => 'Not Aktif (Broken/Eliminated)',
            '3W2P11' => 'Not Aktif (Broken/Eliminated)',
            '4K3P41' => 'Not Aktif (Broken/Eliminated)',
            '4K3P51' => 'Not Aktif (Broken/Eliminated)',
            '5K1P01' => 'Not Aktif (Broken/Eliminated)',

            // =========================
            // READY STANDBY
            // =========================
            '2Z1P21' => 'Ready Standby',
            '2Z1S02' => 'Ready Standby',
            '3Z2P10' => 'Ready Standby',
            '3Z2P11' => 'Ready Standby',
            '3Z2P21' => 'Ready Standby',
            '3Z2P31' => 'Ready Standby',
            '3Z2P41' => 'Ready Standby',
            '3Z2P51' => 'Ready Standby',
            '3Z2P52' => 'Ready Standby',
            '3Z2P61' => 'Ready Standby',
            '3Z2P62' => 'Ready Standby',
            '3Z2P63' => 'Ready Standby',
            '3Z2P71' => 'Ready Standby',
            '3Z2P72' => 'Ready Standby',
            '3Z2P73' => 'Ready Standby',
            '3Z2P81' => 'Ready Standby',
            '3Z2P91' => 'Ready Standby',
            '3Z2S02' => 'Ready Standby',
            '4W1P91' => 'Ready Standby',
            '4W1P81' => 'Ready Standby',
            '4W1P71' => 'Ready Standby',
            '4W1P61' => 'Ready Standby',
            '4W1P51' => 'Ready Standby',
            '4W1P31' => 'Ready Standby',
            '4W1P11' => 'Ready Standby',
            '4R2P91' => 'Ready Standby',
            '4R2P71' => 'Ready Standby',
            '4R2P61' => 'Ready Standby',
            '4R2P51' => 'Ready Standby',
            '4R2P41' => 'Ready Standby',
            '4R2P31/36' => 'Ready Standby',
            '4R2P21' => 'Ready Standby',
            '4R2P11' => 'Ready Standby',
            '4R1P12' => 'Ready Standby',
            '4K3P71' => 'Ready Standby',
            '4K3P61' => 'Ready Standby',
            '4K3P31' => 'Ready Standby',
            '4K3P11' => 'Ready Standby',
            '4K3P01' => 'Ready Standby',
            '4K2P11' => 'Ready Standby',
            '4J2P21' => 'Ready Standby',
            '4J2P11' => 'Ready Standby',
            '4J1P21' => 'Ready Standby',
            '4J1P11' => 'Ready Standby',

            // =========================
            // ACTIVE OPERATION
            // =========================
            '4Z2P91' => 'Active Operation',
            '4Z2P81' => 'Active Operation',
            '4Z2P71' => 'Active Operation',
            '4Z2P51' => 'Active Operation',
            '4Z2P41' => 'Active Operation',
            '4Z2P11' => 'Active Operation',
            '4Z2P106' => 'Active Operation',
            '4Z2P06' => 'Active Operation',
            '4Z1P95' => 'Active Operation',
            '4Z1P91' => 'Active Operation',
            '4Z1P71' => 'Active Operation',
            '4Z1P66' => 'Active Operation',
            '4Z1P52' => 'Active Operation',
            '4Z1P41' => 'Active Operation',
            '4Z1P21' => 'Active Operation',
            '4Z1P172' => 'Active Operation',
            '4Z1P162' => 'Active Operation',
            '4Z1P152' => 'Active Operation',
            '4Z1P142' => 'Active Operation',
            '4Z1P132' => 'Active Operation',
            '4Z1P122' => 'Active Operation',
            '4Z1P112' => 'Active Operation',
            '4Z1P11' => 'Active Operation',
            '4Z1P01' => 'Active Operation',
            '4U1P48' => 'Active Operation',
            '4U1P41' => 'Active Operation',
            '5Z2P55' => 'Active Operation',
            '5Z2P50' => 'Active Operation',
            '5Z2P40' => 'Active Operation',
            '5Z2P30' => 'Active Operation',
            '5Z2P20' => 'Active Operation',
            '5Z2P10' => 'Active Operation',
            '5Z2P01' => 'Active Operation',
            '5Z1P61' => 'Active Operation',
            '5Z1P55' => 'Active Operation',
            '5Z1P50' => 'Active Operation',
            '5Z1P40' => 'Active Operation',
            '5Z1P30' => 'Active Operation',
            '5Z1P20' => 'Active Operation',
            '5Z1P10' => 'Active Operation',
            '5Z1P01' => 'Active Operation',
            '5W1P21' => 'Active Operation',
            '5W1P11' => 'Active Operation',
            '5W1P01' => 'Active Operation',
            '5U1P65' => 'Active Operation',
            '5U1P61' => 'Active Operation',
            '5U1P51' => 'Active Operation',
            '5U1P41' => 'Active Operation',
            '5U1P31' => 'Active Operation',
            '5U1P21' => 'Active Operation',
            '5U1P165' => 'Active Operation',
            '5U1P11' => 'Active Operation',
            '5U1P01' => 'Active Operation',
            '5R2P41' => 'Active Operation',
            '5R2P04' => 'Active Operation',
            '5R2P01' => 'Active Operation',
            '5R1P91' => 'Active Operation',
            '5R1P01' => 'Active Operation',
            '5K1P71' => 'Active Operation',
            '5K1P51' => 'Active Operation',
            '5K1P31' => 'Active Operation',
            '5K1P11' => 'Active Operation',
            '5J1P51' => 'Active Operation',
            '5J1P01' => 'Active Operation',
            '5H1P01' => 'Active Operation',
            '6Z1P81' => 'Active Operation',
            '6Z1P71' => 'Active Operation',
            '6Z1P61' => 'Active Operation',
            '6Z1P51' => 'Active Operation',
            '6Z1P41' => 'Active Operation',
            '6Z1P31' => 'Active Operation',
            '6Z1P21' => 'Active Operation',
            '6Z1P11' => 'Active Operation',
            '6Z1P01' => 'Active Operation',
            '6W1P51' => 'Active Operation',
            '6W1P31' => 'Active Operation',
            '6W1P21' => 'Active Operation',
            '6W1P11' => 'Active Operation',
            '6W1P01' => 'Active Operation',
            '6U1P81' => 'Active Operation',
            '6U1P71' => 'Active Operation',
            '6U1P61' => 'Active Operation',
            '6U1P51' => 'Active Operation',
            '6U1P41' => 'Active Operation',
            '6U1P31' => 'Active Operation',
            '6U1P21' => 'Active Operation',
            '6U1P11' => 'Active Operation',
            '6U1P01' => 'Active Operation',
            '6R1P81' => 'Active Operation',
            '6R1P71' => 'Active Operation',
            '6R1P61' => 'Active Operation',
            '6R1P51' => 'Active Operation',
            '6R1P31' => 'Active Operation',
            '6R1P21' => 'Active Operation',
            '6R1P11' => 'Active Operation',
            '6P2P12' => 'Active Operation',
            '6P1P11' => 'Active Operation',
            '6K1P60' => 'Active Operation',
            '6K1P51' => 'Active Operation',
            '6K1P11' => 'Active Operation',
            '6J1P01' => 'Active Operation',
        ];

        foreach ($map as $code => $status) {
            $nomen = Nomenclature::where('name', $code)->first();

            if ($nomen) {
                $nomen->update([
                    'default_status' => $status
                ]);
            }
        }
    }
}