<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Plant;
use App\Models\Area;
use App\Models\Nomenclature;

class NomenclatureSeeder extends Seeder
{
    public function run()
    {
        $rows = [

            // --------------------- INDARUNG 23 ---------------------
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '2H1P11',  'desc' => 'JPF - Top Silo H1'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '2H1P21',  'desc' => 'JPF - Top Silo H1'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2J1P11',  'desc' => 'ESP Raw mill'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2J1P21',  'desc' => 'ESP Raw mill'],
            ['plant' => 'Indarung 23', 'area' => 'Coal Mill',       'code' => '2K1S02',  'desc' => 'BHF Coal mill K1'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '2R1P21',  'desc' => 'JPF - Separator R1'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2U1P01',  'desc' => 'Bottom U1J05'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2U1P11',  'desc' => 'Outlet DC U1U01'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2U1P21',  'desc' => 'Elevator U1J05'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2U1P31',  'desc' => 'Midle DC U1U01'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2U1P51',  'desc' => 'Elevator U1J05'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2U1P81',  'desc' => 'Main Drive W1U09'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2W1P11',  'desc' => 'Kiln feed W1'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2W1P21',  'desc' => 'DC W1U04-05'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2W1P31',  'desc' => 'LBC W1U06'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2W1P33',  'desc' => 'Elevator W1U08 - W2U08'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '2W1P41',  'desc' => 'Clinker Intake'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '2Z1P21',  'desc' => 'O-Sepa Z1'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '2Z1S02',  'desc' => 'BHF O-Sepa Z1'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3H2P11',  'desc' => 'Top silo H2'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3H2P21',  'desc' => 'Top silo H2'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3J2P11',  'desc' => 'ESP Raw mill'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3J2P21',  'desc' => 'ESP Raw mill'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3J2P31',  'desc' => 'ESP Raw mill'],
            ['plant' => 'Indarung 23', 'area' => 'Coal Mill',       'code' => '3K2S02',  'desc' => 'BHF Coal mill K2'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3P1P11',  'desc' => 'Puncak Silo II'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3P1P21',  'desc' => 'Puncak Silo I'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3P1P31',  'desc' => 'Puncak Silo III'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3P1P41',  'desc' => 'Puncak Silo IV'],
            ['plant' => 'Indarung 23', 'area' => 'Raw Mill',        'code' => '3R2P21',  'desc' => 'Separator R2'],
            ['plant' => 'Indarung 23', 'area' => 'SP-KILN-Cooler',  'code' => '3W2P11',  'desc' => 'Kiln feed W2'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P10',  'desc' => 'DDS CM'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P11',  'desc' => 'BHF Cement Mill'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P21',  'desc' => 'O-Sepa Z2'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P31',  'desc' => 'Inlet Z2U25 Baru'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P41',  'desc' => 'Inlet Z2U25'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P51',  'desc' => 'Inlet Z2U24'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P52',  'desc' => 'Outlet Z2U25'],

            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P61',  'desc' => 'Outlet Z2U25'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P62',  'desc' => 'Pangkal 4Z2U27'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P63',  'desc' => 'Belt Z2J12'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P71',  'desc' => 'Belt TC 3Z2U27'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P72',  'desc' => 'Elevator PG'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P73',  'desc' => 'Outlet Z3U27'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P81',  'desc' => 'elevator Z2J21/Z2M21'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2P91',  'desc' => 'DC U1U01'],
            ['plant' => 'Indarung 23', 'area' => 'Finish Mill',     'code' => '3Z2S02',  'desc' => 'BHF O-Sepa Z2'],
            ['plant' => 'Indarung 23', 'area' => 'Coal Mill',       'code' => '4K3P41',  'desc' => 'Bin Fine coal Ind3'],
            ['plant' => 'Indarung 23', 'area' => 'Coal Mill',       'code' => '4K3P51',  'desc' => 'Bin Fine coal Ind2'],

            // --------------------- INDARUNG 4 ---------------------
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P91',  'desc' => 'JPF - Elevator J01'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P81',  'desc' => 'JPF - Ducting Sirkulasi Sepak'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P71',  'desc' => 'JPF - Ducting Sirkulasi Sepak Add'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P51',  'desc' => 'JPF - Belt Conv A05'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P41',  'desc' => 'JPF - Belt Conv A05'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P11',  'desc' => 'ESP Cemen Mill'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P106', 'desc' => 'JPF - Belt Conv U24'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z2P06',  'desc' => 'JPF - Hopper Clinker'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P95',  'desc' => 'DDS - Belt Conv A02'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P91',  'desc' => 'JPF - to Screw J15 (Hopper)'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P71',  'desc' => 'JPF - Cement Silo 4'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P66',  'desc' => 'DDS - Belt Conv A02'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P52',  'desc' => 'DDS - Belt Conv Out U41'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P41',  'desc' => 'DDS - Belt Conv Out U41'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P21',  'desc' => 'JPF - Lantai Roller Press'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P172', 'desc' => 'DDS - TC U25'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P162', 'desc' => 'DDS - TC U27'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P152', 'desc' => 'DDS - Cement Silo 8'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P142', 'desc' => 'DDS - Cement Silo 7'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P132', 'desc' => 'DDS - Belt Conv Inlet Mill J02'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P122', 'desc' => 'DDS - Feed A07'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P112', 'desc' => 'DDS - Belt Conv A05 Clinker'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P11',  'desc' => 'ESP CM'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4Z1P01',  'desc' => 'BHF Cement Mill'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P91',  'desc' => 'JPF - Klinker & Cement Transport'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P81',  'desc' => 'JPF - Silo Clinker 3B'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P71',  'desc' => 'JPF - Silo Clinker 3C'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P61',  'desc' => 'JPF - Silo Clinker 3B'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P51',  'desc' => 'JPF - Silo Intermediet'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P31',  'desc' => 'JPF - DLD Tank Kiln Feed'],
            ['plant' => 'Indarung 4', 'area' => 'SP-KILN-Cooler',   'code' => '4W1P11',  'desc' => 'ESP Cooler'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4U1P48',  'desc' => 'DDS - Belt Conv Klinker'],
            ['plant' => 'Indarung 4', 'area' => 'Finish Mill',      'code' => '4U1P41',  'desc' => 'JPF - Belt Conv Clinker'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P91',  'desc' => 'JPF - CF Silo'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P71',  'desc' => 'JPF RM Transport reject'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P61',  'desc' => 'DDS - Belt Conv Out J10'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P51',  'desc' => 'DDS - Belt Conv Out J03'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P41',  'desc' => 'DDS - Belt Conv Out J12'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P31/36', 'desc' => 'JPF - Bottom Elevator U15'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P21',  'desc' => 'DDS - Outlet Reject Mill J10'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R2P11',  'desc' => 'JPF - Air Slide U06'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4R1P12',  'desc' => 'JPF - Air Slide U02'],
            ['plant' => 'Indarung 4', 'area' => 'Coal Mill',        'code' => '4K3P71',  'desc' => 'JPF - Bin Fine Coal'],
            ['plant' => 'Indarung 4', 'area' => 'Coal Mill',        'code' => '4K3P61',  'desc' => 'DDS - Dust Pump'],
            ['plant' => 'Indarung 4', 'area' => 'Coal Mill',        'code' => '4K3P31',  'desc' => 'JPF - Bin Fine Coal'],
            ['plant' => 'Indarung 4', 'area' => 'Coal Mill',        'code' => '4K3P11',  'desc' => 'BHF Coal Mill 4K3'],
            ['plant' => 'Indarung 4', 'area' => 'Coal Mill',        'code' => '4K3P01',  'desc' => 'DDS - Hopper Raw Coal'],
            ['plant' => 'Indarung 4', 'area' => 'Coal Mill',        'code' => '4K2P11',  'desc' => 'ESP Coal Mill'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4J2P21',  'desc' => 'JPF - Air slide to Screw U22'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4J2P11',  'desc' => 'BHF Raw Mill 3C'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4J1P21',  'desc' => 'ESP RM 3B'],
            ['plant' => 'Indarung 4', 'area' => 'Raw Mill',         'code' => '4J1P11',  'desc' => 'ESP RM 3B'],

            // --------------------- INDARUNG 5 ---------------------
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P55',  'desc' => 'JPF - Silo Semen 12'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P50',  'desc' => 'JPF - Silo Semen 11'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P40',  'desc' => 'JPF - Bottom Elevator Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P30',  'desc' => 'JPF - Venting Ducting Circ'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P20',  'desc' => 'JPF - Belt Conveyor Inlet Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P10',  'desc' => 'JPF - Belt Conveyor Out RP'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z2P01',  'desc' => 'ESP Finish Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P61',  'desc' => 'JPF - Top Elevator Silo'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P55',  'desc' => 'JPF - Silo Semen 9'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P50',  'desc' => 'JPF - Silo Semen 10'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P40',  'desc' => 'JPF - Bottom Elevator Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P30',  'desc' => 'JPF - Venting Ducting Circ'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P20',  'desc' => 'JPF - Belt Conveyor Inlet Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P10',  'desc' => 'JPF - Belt Conveyor Out RP'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5Z1P01',  'desc' => 'ESP Finish Mill'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5W1P21',  'desc' => 'ESP Cooler'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5W1P11',  'desc' => 'JPF - Elevator Kiln Feed (U27&A17)'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5W1P01',  'desc' => 'JPF - DLD Tank Kiln Feed'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5U1P65',  'desc' => 'JPF - Belt Conveyor TC'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5U1P61',  'desc' => 'JPF - Belt Conveyor TC'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5U1P51',  'desc' => 'JPF - Belt Conveyor TC'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5U1P41',  'desc' => 'JPF - Appron Klinker J03-J04 (Intake Klinker)'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5U1P31',  'desc' => 'JPF - Apron - Belt Conveyor'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5U1P21',  'desc' => 'JPF - Apron - Belt Conveyor'],
            ['plant' => 'Indarung 5', 'area' => 'Finish Mill',      'code' => '5U1P165', 'desc' => 'JPF - Belt Conv Finish Mill'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5U1P11',  'desc' => 'JPF - Unburn Silo Klinker'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5U1P01',  'desc' => 'JPF - Dome Silo Klinker'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5R2P41',  'desc' => 'JPF - Air Slide U06 (Produk Raw Mix)'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5R2P04',  'desc' => 'JPF - Reject Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5R2P01',  'desc' => 'DDS - Belt Conveyor Reject RM'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5R1P91',  'desc' => 'JPF - Top CF Silo'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5R1P01',  'desc' => 'DDS - Belt Conveyor Reject RM'],
            ['plant' => 'Indarung 5', 'area' => 'Coal Mill',        'code' => '5K1P71',  'desc' => 'JPF - Siklo Header TFC'],
            ['plant' => 'Indarung 5', 'area' => 'Coal Mill',        'code' => '5K1P51',  'desc' => 'JPF - Bin Fine Coal'],
            ['plant' => 'Indarung 5', 'area' => 'Coal Mill',        'code' => '5K1P31',  'desc' => 'JPF - CoM Screw Conv'],
            ['plant' => 'Indarung 5', 'area' => 'Coal Mill',        'code' => '5K1P11',  'desc' => 'ESP Coal Mill'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5K1P01',  'desc' => 'BHF Coal Mill'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5J1P51',  'desc' => 'JPF - Dragchain U14'],
            ['plant' => 'Indarung 5', 'area' => 'Raw Mill',         'code' => '5J1P01',  'desc' => 'ESP Rawmill'],
            ['plant' => 'Indarung 5', 'area' => 'SP-KILN-Cooler',   'code' => '5H1P01',  'desc' => 'JPF - Elevator Raw Mill (U22&U27)'],

            // --------------------- INDARUNG 6 ---------------------
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P81',  'desc' => 'JPF - Fly Ash Cement Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P71',  'desc' => 'JPF - Elevator Silo CM'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P61',  'desc' => 'JPF- Venting Air Slide CM Transport'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P51',  'desc' => 'JPF - Reject Belt Conv CM'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P41',  'desc' => 'BHF Cement Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P31',  'desc' => 'JPF - Belt Conv Inlet Cement Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P21',  'desc' => 'JPF - Elevator J10 & Belt Conv.'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P11',  'desc' => 'JPF - CM Feed Belt Conv J01'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6Z1P01',  'desc' => 'JPF - CM Feed Reject'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6W1P51',  'desc' => 'ESP Cooler'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6W1P31',  'desc' => 'JPF - Elevator U17&A12 Top Kiln Feed'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6W1P21',  'desc' => 'JPF - Elevator A12 Top Kiln Feed'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6W1P11',  'desc' => 'JPF - Bott. Kiln Feed Elevator'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6W1P01',  'desc' => 'JPF - Bott. Kiln Feed Elevator'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P81',  'desc' => 'JPF - Clinker Transport'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P71',  'desc' => 'JPF - Clinker Hopper'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P61',  'desc' => 'JPF - Clinker Transport'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P51',  'desc' => 'JPF - Clinker Transport'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P41',  'desc' => 'JPF - Clinker Transport'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P31',  'desc' => 'JPF - Clinker Dumping'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6U1P21',  'desc' => 'JPF - Unburn Silo'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6U1P11',  'desc' => 'JPF - Top Clinker Silo'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6U1P01',  'desc' => 'JPF - DBC Cooler'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6R1P81',  'desc' => 'JPF - Top CF-Silo'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6R1P71',  'desc' => 'JPF - Elevator U17 & Top Kiln Feed'],
            ['plant' => 'Indarung 6', 'area' => 'SP-KILN-Cooler',   'code' => '6R1P61',  'desc' => 'JPF - U07 & Top Preheater'],
            ['plant' => 'Indarung 6', 'area' => 'Raw Mill',         'code' => '6R1P51',  'desc' => 'JPF - Venting Air Slide& U07 Raw Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Raw Mill',         'code' => '6R1P31',  'desc' => 'JPF - Venting Air Slide Raw Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Raw Mill',         'code' => '6R1P21',  'desc' => 'JPF - Hopper Reject Raw Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Raw Mill',         'code' => '6R1P11',  'desc' => 'JPF - Elevator J09 Raw Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6P2P12',  'desc' => 'JPF - Silo Cement 14'],
            ['plant' => 'Indarung 6', 'area' => 'Finish Mill',      'code' => '6P1P11',  'desc' => 'JPF - Silo Cement 13'],
            ['plant' => 'Indarung 6', 'area' => 'Coal Mill',        'code' => '6K1P60',  'desc' => 'DDS- Transport Fine Coal'],
            ['plant' => 'Indarung 6', 'area' => 'Coal Mill',        'code' => '6K1P51',  'desc' => 'JPF - Top Bin Fine Coal'],
            ['plant' => 'Indarung 6', 'area' => 'Coal Mill',        'code' => '6K1P11',  'desc' => 'BHF Coal Mill'],
            ['plant' => 'Indarung 6', 'area' => 'Raw Mill',         'code' => '6J1P01',  'desc' => 'BHF Raw Mill'],

        ];

        // ---------------------------------------------------------
        // LOOP UTAMA → SIMPAN KE DATABASE
        // ---------------------------------------------------------

        foreach ($rows as $row) {

            $plant = Plant::firstOrCreate(['name' => $row['plant']]);

            $area = Area::firstOrCreate([
                'plant_id' => $plant->id,
                'name'     => $row['area'],
            ]);

            Nomenclature::firstOrCreate([
                'plant_id'    => $plant->id,
                'area_id'     => $area->id,
                'name'        => $row['code'],
                'description' => $row['desc'],
            ]);
        }
    }
}
